name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Test Function
      id: test-function
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Function
        setup-command: ''
        command: python -m unittest tests/testFunction.py
        timeout: 1
        max-score: 1
    - name: Test Data Length
      id: test-data-length
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Data Length
        setup-command: ''
        command: python -m unittest tests/testDataLength.py
        timeout: 1
        max-score: 1
    - name: Test Listing
      id: test-listing
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Listing
        setup-command: ''
        command: python -m unittest tests/testColumnListing.py
        timeout: 1
        max-score: 1
    - name: Test Price
      id: test-price
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Price
        setup-command: ''
        command: python -m unittest tests/testColumnPrice.py
        timeout: 1
        max-score: 1
    - name: Test Brand
      id: test-brand
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Brand
        setup-command: ''
        command: python -m unittest tests/testColumnBrand.py
        timeout: 1
        max-score: 1
    - name: Test Size
      id: test-size
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Size
        setup-command: ''
        command: python -m unittest tests/testColumnSize.py
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FUNCTION_RESULTS: "${{steps.test-function.outputs.result}}"
        TEST-DATA-LENGTH_RESULTS: "${{steps.test-data-length.outputs.result}}"
        TEST-LISTING_RESULTS: "${{steps.test-listing.outputs.result}}"
        TEST-PRICE_RESULTS: "${{steps.test-price.outputs.result}}"
        TEST-BRAND_RESULTS: "${{steps.test-brand.outputs.result}}"
        TEST-SIZE_RESULTS: "${{steps.test-size.outputs.result}}"
      with:
        runners: test-function,test-data-length,test-listing,test-price,test-brand,test-size
